demo/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),

] 

home/urls.py
from . import views
from django.urls import path
from .views import  contactView, successView

urlpatterns = [
    path('index/', views.index, name="index"), 
    path('', views.about, name="about"),
    path('blog/', views.blog, name="blog"),
    path('featured/', views.featured, name="featured"), 
    path("contact/", contactView, name="contact"),
    path("success/", successView, name="success"),
]
    

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserModel (models.Model):
    username = models.CharField(max_length=200)
    password = models.IntegerField()
    re_password = models.IntegerField()

    class meta:
        models = User
        fields = ["username", "password", "re_password"]

home/forms.py
# sendemail/forms.py
from django import forms

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

home/views.py
from django.shortcuts import render
from .models import UserModel
from django.http import HttpResponse

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm

# Create your views here.

def index (request):
    return render(request, 'auth/index.html')

def about (request):
    return render(request, 'informations/about.html')

def blog (request):
    return render(request, 'informations/blog.html' )

def contact (request):
    return render(request, 'informations/contact.html')

def featured (request):
    return render(request, 'informations/featured.html' )

# def success(request):
#     email = request.POST.get('email', '')
#     data = """
#         Hello! I am Phuc.
#     """
#     send_mail('Welcome!', data, "PLC", [email], fail_silently=False)
#     return render(request, 'send_email/success.html')
# def main(request):
#     return render(request, 'send_email/main.html')

def contactView(request):
    if request.method == "GET":
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data["subject"]
            from_email = form.cleaned_data["from_email"]
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ["lhuy211102@gmail.com"])
            except BadHeaderError:
                return HttpResponse("Invalid header found.")
            return redirect("contact")
    return render(request, "informations/contact.html", {"form": form})

def successView(request):
    return HttpResponse("Success! Thank you for your message.")

templates/informations/about.html
<html>
<head>
    {% load static %}
    {% include 'auth/index.html' %}
    <meta charset="utf-8">
    <title>About me</title>
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
    <!-- <link rel="stylesheet" href="{% static 'js/first.js' %}"> -->

</head>

</head>
<body>
    <div class="informations">
        <h1 class="about-me">about me</h1>
        <div class="text-about-me">
            <h2 style="font-size: 1.6pc;">
                I`m a Huy Designer and Full Stack
                <br>
                Developer from Bac Giang, Viet Nam.
            </h2>
            <br>
            I enjoy turning complex problems into simple, 
            <br>
            beautiful and intuitive interface designs. When I'm 
            <br>
            not coding or pushing pixels, you'll find me in the 
            <br>
            gym or on the court shooting hoops
        </div>
    </div>


</body>
</html>

templates/informations/blog.html
<html>
<head>
    {% load static %}
    {% include 'auth/index.html' %}
    <meta charset="utf-8">
    <title>Blog</title>
</head>
<body>
    <div class="about-us">  
        <h2 id="title-about">Giới thiệu</h2>
        <div class="form-contact">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z"/>
                <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z"/>
            </svg>
            Từng học tại <a style="text-decoration: none; color: white;" href="https://thanglong.edu.vn/">Thăng Long University</a><br>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z"/>
                <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z"/>
            </svg>
            Đã học tại <a style="text-decoration: none; color: white;" href="http://thptyendung2.bacgiang.edu.vn/">Trường THPT Yên Dũng Số 2</a><br>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z"/>
                <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z"/>
            </svg>
            Sống tại <a style="text-decoration: none; color: white;" href="http://www.hanoimoi.com.vn/">Hà Nội</a><br>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z"/>
                <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z"/>
            </svg>
            Đến từ <a style="text-decoration: none; color: white; " href="https://vi.wikipedia.org/wiki/B%E1%BA%AFc_Giang">Bắc giang</a><br>

            <span>
                &emsp;&emsp;&emsp;<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock-history" viewBox="0 0 16 16">
                    <path d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022l-.074.997zm2.004.45a7.003 7.003 0 0 0-.985-.299l.219-.976c.383.086.76.2 1.126.342l-.36.933zm1.37.71a7.01 7.01 0 0 0-.439-.27l.493-.87a8.025 8.025 0 0 1 .979.654l-.615.789a6.996 6.996 0 0 0-.418-.302zm1.834 1.79a6.99 6.99 0 0 0-.653-.796l.724-.69c.27.285.52.59.747.91l-.818.576zm.744 1.352a7.08 7.08 0 0 0-.214-.468l.893-.45a7.976 7.976 0 0 1 .45 1.088l-.95.313a7.023 7.023 0 0 0-.179-.483zm.53 2.507a6.991 6.991 0 0 0-.1-1.025l.985-.17c.067.386.106.778.116 1.17l-1 .025zm-.131 1.538c.033-.17.06-.339.081-.51l.993.123a7.957 7.957 0 0 1-.23 1.155l-.964-.267c.046-.165.086-.332.12-.501zm-.952 2.379c.184-.29.346-.594.486-.908l.914.405c-.16.36-.345.706-.555 1.038l-.845-.535zm-.964 1.205c.122-.122.239-.248.35-.378l.758.653a8.073 8.073 0 0 1-.401.432l-.707-.707z"/>
                    <path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0v1z"/>
                    <path d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z"/>
                </svg>
                <a href="" style="text-decoration: none; color: white; font-family: cursive;">Đọc truyện tranh </a>
            </span>

            
            &emsp;&emsp;&emsp;<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-sunglasses" viewBox="0 0 16 16">
                <path d="M3 5a2 2 0 0 0-2 2v.5H.5a.5.5 0 0 0 0 1H1V9a2 2 0 0 0 2 2h1a3 3 0 0 0 3-3 1 1 0 1 1 2 0 3 3 0 0 0 3 3h1a2 2 0 0 0 2-2v-.5h.5a.5.5 0 0 0 0-1H15V7a2 2 0 0 0-2-2h-2a2 2 0 0 0-1.888 1.338A1.99 1.99 0 0 0 8 6a1.99 1.99 0 0 0-1.112.338A2 2 0 0 0 5 5H3zm0 1h.941c.264 0 .348.356.112.474l-.457.228a2 2 0 0 0-.894.894l-.228.457C2.356 8.289 2 8.205 2 7.94V7a1 1 0 0 1 1-1z"/>
              </svg>
            <a href="" style="text-decoration: none; color: white;font-family: cursive; ">Nấu ăn</a><br>

            &emsp;&emsp;&emsp;<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-controller" viewBox="0 0 16 16">
                <path d="M11.5 6.027a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zm2.5-.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zm-6.5-3h1v1h1v1h-1v1h-1v-1h-1v-1h1v-1z"/>
                <path d="M3.051 3.26a.5.5 0 0 1 .354-.613l1.932-.518a.5.5 0 0 1 .62.39c.655-.079 1.35-.117 2.043-.117.72 0 1.443.041 2.12.126a.5.5 0 0 1 .622-.399l1.932.518a.5.5 0 0 1 .306.729c.14.09.266.19.373.297.408.408.78 1.05 1.095 1.772.32.733.599 1.591.805 2.466.206.875.34 1.78.364 2.606.024.816-.059 1.602-.328 2.21a1.42 1.42 0 0 1-1.445.83c-.636-.067-1.115-.394-1.513-.773-.245-.232-.496-.526-.739-.808-.126-.148-.25-.292-.368-.423-.728-.804-1.597-1.527-3.224-1.527-1.627 0-2.496.723-3.224 1.527-.119.131-.242.275-.368.423-.243.282-.494.575-.739.808-.398.38-.877.706-1.513.773a1.42 1.42 0 0 1-1.445-.83c-.27-.608-.352-1.395-.329-2.21.024-.826.16-1.73.365-2.606.206-.875.486-1.733.805-2.466.315-.722.687-1.364 1.094-1.772a2.34 2.34 0 0 1 .433-.335.504.504 0 0 1-.028-.079zm2.036.412c-.877.185-1.469.443-1.733.708-.276.276-.587.783-.885 1.465a13.748 13.748 0 0 0-.748 2.295 12.351 12.351 0 0 0-.339 2.406c-.022.755.062 1.368.243 1.776a.42.42 0 0 0 .426.24c.327-.034.61-.199.929-.502.212-.202.4-.423.615-.674.133-.156.276-.323.44-.504C4.861 9.969 5.978 9.027 8 9.027s3.139.942 3.965 1.855c.164.181.307.348.44.504.214.251.403.472.615.674.318.303.601.468.929.503a.42.42 0 0 0 .426-.241c.18-.408.265-1.02.243-1.776a12.354 12.354 0 0 0-.339-2.406 13.753 13.753 0 0 0-.748-2.295c-.298-.682-.61-1.19-.885-1.465-.264-.265-.856-.523-1.733-.708-.85-.179-1.877-.27-2.913-.27-1.036 0-2.063.091-2.913.27z"/>
            </svg>
            <a href="" style="text-decoration: none; color: white;font-family: cursive;">Game</a>



            &emsp;&emsp;&emsp;<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-fire" viewBox="0 0 16 16">
                <path d="M8 16c3.314 0 6-2 6-5.5 0-1.5-.5-4-2.5-6 .25 1.5-1.25 2-1.25 2C11 4 9 .5 6 0c.357 2 .5 4-2 6-1.25 1-2 2.729-2 4.5C2 14 4.686 16 8 16Zm0-1c-1.657 0-3-1-3-2.75 0-.75.25-2 1.25-3C6.125 10 7 10.5 7 10.5c-.375-1.25.5-3.25 2-3.5-.179 1-.25 2 1 3 .625.5 1 1.364 1 2.25C11 14 9.657 15 8 15Z"/>
            </svg>
            <a href="" style="text-decoration: none; color: white;font-family: cursive;">Chạy bộ</a><br>
        </div>
    </div>

</body>
</html>

templates/informations/contact.html
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <title>Contact</title>
    {% include 'auth/index.html' %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>
<body>
    <div class="form-email" style="margin-left: 2cm; margin-top: -1170px; background-color: rgb(192, 192, 192); border-radius: 10px; height: 10cm; width: 15cm;">
        <h1 style="margin-left: 4.8cm;">Contact Us</h1>
        <form method="post" style="margin-left: 0.5cm;">
            {% csrf_token %}
            <!-- {{ form.as_p }} -->
            <p>
                <label for="id_from_email" style="font-size: 1.3pc;">From email:</label>
                <input style="margin-left:0.9cm; width: 9.1cm;"  type="email" name="from_email" required id="id_from_email">
            </p>

            
            <p>
                <label for="id_subject" style="font-size: 1.3pc;">Subject:</label>
                <input style="margin-left: 1.8cm; width: 9.1cm;" type="text" name="subject" required id="id_subject">
            </p>

            
            <p>
                <label for="id_message" style="font-size: 1.3pc;">Message:</label>
                <textarea style="margin-left: 1.5cm; width: 9.1cm;" name="message" cols="40" rows="10" required id="id_message"> </textarea>
            </p>

            <div class="form-actions">
                <button type="submit" style="margin-left: 4cm; width: 4cm; height: 1cm; border-radius: 10px; font-size: 1.3pc; font-family: monospace;"  >Send</button>
            </div>
        </form>
    </div>

</body>
</html>

templates/informations/featured.html
<html>
<head>
    {% load static %}
    {% include 'auth/index.html' %}
    <meta charset="utf-8">
    <title>Featured</title>
    <script src="{% static 'js/main.js' %}">

    </script>
    
</head>
<body>
    <button onclick="outWin()" type="button">click</button>
</body>
</html>